POST http://localhost:8080/events/many
Content-Type: application/json

{
    "event1": {
       "name": "Test event",
    "author": "hybwiufbwokfujb",
    "description": "A test event"
    },
    "event2": {
        "name": "Test event",
    "author": "hybwiufbwokfujb",
    "description": "A test event"
    },
    "event3": {
        "name": "Test event",
    "author": "hybwiufbwokfujb",
    "description": "A test event"
    }
}
